project:
  project-id: fl68a28cf3527c0b1c6be7ab
  project-name: wmio_test_gen_support
  external-git:
    enabled: true
    repository: chini007/wmio_test_gen_supportProject
    api-repository-path: chini007/Wmio_test_gen_supportProject
    branch: dev
    account-alias: insrsa_github
